[package]
name = "algorithm-visualizer"
version = "0.1.0"
edition = "2021"
authors = ["Caio Petrucci"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19"