[package]
name = "algorithm-visualizer"
version = "0.1.0"
edition = "2018"
authors = ["Caio Petrucci", "Daniel Hosomi"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
